import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'John',
      email: 'john@example.com',
      password: bcrypt.hashSync('12345'),
      isAdmin: true,
    },
    {
      name: 'Amon',
      email: 'amon@example.com',
      password: bcrypt.hashSync('12346'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirt',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      raging: 4.5,
      numReviews: 1,
      countInStock: 20,
      description: 'A popular Shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirt',
      image: '/images/shirt2.jpg',
      price: 60,
      brand: 'Adidas',
      raging: 4.8,
      numReviews: 3,
      countInStock: 25,
      description: 'A popular Shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirt',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Banana',
      raging: 3.5,
      numReviews: 11,
      countInStock: 10,
      description: 'A popular Shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'pants',
      image: '/images/pants1.jpg',
      price: 65,
      brand: 'Oliver',
      raging: 4.1,
      numReviews: 16,
      countInStock: 16,
      description: 'Smart Looking Pants',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'pants',
      image: '/images/pants2.jpg',
      price: 80,
      brand: 'Zara',
      raging: 4.4,
      numReviews: 17,
      countInStock: 24,
      description: 'A popular pants',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'pants',
      image: '/images/pants3.jpg',
      price: 70,
      brand: 'Nike',
      raging: 4.5,
      numReviews: 1,
      countInStock: 20,
      description: 'A popular Shirt',
    },
  ],
};
export default data;
